version: 0.1

phases:
  install:
    commands:
      - echo Entering install phase...
      - echo Nothing to do now
  build:
    commands:
      - echo Build Engine started on `date`
      - gradle -p engine build
artifacts:
  type: jar
  files:
    - 'Engine/build/distributions/Engine-shadow-1.0-SNAPSHOT.tar'