FROM gradle:7.1.0-jdk11 as builder
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src/Game
RUN gradle shadowJar

FROM openjdk:11-jre-slim
EXPOSE 8080
ENV VERTICLE_FILE Game-1.0-SNAPSHOT-all.jar

COPY --from=builder /home/gradle/src/Game/build/libs/$VERTICLE_FILE /
WORKDIR /
ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar $VERTICLE_FILE"]