openapi: 3.0.0

info:
  title: Burraco Game APIs
  version: 0.0.1

servers:
  - url: "{protocol}://{address}:{port}"
    description: Game Service address
    variables:
      address:
        default: localhost
        description: Address of the server
      port:
        default: "8081"
        description: Port of the server
      protocol:
        default: http
        description: Protocol for interacting with server
        enum:
          - http

paths:
  /games/{gameId}:
    get:
      operationId: 'gameInfo'
      summary: 'Game info'
      description: 'Public API to see the game details'
      tags:
        - Game
        - Public
      parameters:
        - name: 'gameId'
          description: 'Game identifier'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: '#/components/responses/GameResponse'

components:
  schemas:
    Game:
      type: object
      properties:
        gameId:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - BURRACO
        status:
          type: string
          enum:
            - DRAFT
            - STARTED
            - RUNNING
            - ENDED
        player:
          type: array
          items:
            $ref: "#/components/schemas/PlayerId"
    PlayerId:
      type: string
      format: uuid

  requestBodies:
    NewGameRequest:
      description: 'New Burraco game request.'
      content:
        application/json:
          schema:
            type: object
            required:
              - gameType
            properties:
              gameType:
                type: string
                enum:
                  - BURRACO

    AddPlayerRequest:
      description: 'Add player request.'
      content:
        application/json:
          schema:
            type: object
            required:
              - playerId
            properties:
              playerId:
                $ref: "#/components/schemas/PlayerId"

    InitGameRequest:
      description: 'Add player request.'
      content:
        application/json:
          schema:
            type: object
            required:
              - playerId
            properties:
              playerId:
                $ref: "#/components/schemas/PlayerId"

  responses:
    NewGameResponse:
      description: 'New Burraco game response'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Game'
    GameResponse:
      description: 'Burraco game response'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Game'