openapi: 3.0.0

info:
  title: Burraco Game APIs
  version: 0.0.1

servers:
  - url: "{protocol}://{address}:{port}"
    description: Game Service address
    variables:
      address:
        default: localhost
        description: Address of the server
      port:
        default: "8081"
        description: Port of the server
      protocol:
        default: http
        description: Protocol for interacting with server
        enum:
          - http

paths:
  /health:
    get:
      operationId: 'healthCheck'
      summary: 'Game service Health Check'
      description: 'Public API to monitoring the health of the webservice'
      tags:
        - Public
      responses:
        '200':
          $ref: '#/components/responses/HealthCheckResponse'

  /game/burraco:
    get:
      operationId: 'newGame'
      summary: 'New Burraco game'
      description: 'Public API to create a new game'
      tags:
        - Game
        - Public
      responses:
        '200':
          $ref: '#/components/responses/NewGameResponse'

  /games/{gameId}/player/add:
    post:
      operationId: 'addPlayer'
      summary: 'Add a player to the Game'
      description: 'Public API to Add a player to the game'
      tags:
        - Game
        - Public
      parameters:
        - name: 'gameId'
          description: 'Game identifier'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        $ref: '#/components/requestBodies/AddPlayerRequest'
      responses:
        '200':
          $ref: '#/components/responses/GameResponse'

  /games/{gameId}/requestDealCards:
    post:
      operationId: 'requestDealCards'
      summary: 'Request deal cards'
      description: 'Public API to Initialise the game'
      tags:
        - Game
        - Public
      parameters:
        - name: 'gameId'
          description: 'Game identifier'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        $ref: '#/components/requestBodies/RequestDealCardsRequest'
      responses:
        '200':
          $ref: '#/components/responses/GameResponse'

  /games/{gameId}/start:
    post:
      operationId: 'startGame'
      summary: 'Start the Game'
      description: 'Public API to Start the game'
      tags:
        - Game
        - Public
      parameters:
        - name: 'gameId'
          description: 'Game identifier'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: '#/components/responses/GameResponse'

  /games/{gameId}/pick-up-card:
    post:
      operationId: 'pickUpCard'
      summary: 'Pick up a card from the deck'
      description: 'Public API for a player to pick up a card from the deck during their turn'
      tags:
        - Game
        - Public
      parameters:
        - name: 'gameId'
          description: 'Game identifier'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        $ref: '#/components/requestBodies/PickUpCardRequest'
      responses:
        '200':
          $ref: '#/components/responses/CardResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'

  /games/{gameId}/pick-card-from-discard-deck:
    post:
      operationId: 'pickUpCardsFromDiscardPile'
      summary: 'Pick up cards from the discard pile'
      description: 'Public API for a player to pick up all cards from the discard pile during their turn'
      tags:
        - Game
        - Public
      parameters:
        - name: 'gameId'
          description: 'Game identifier'
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        $ref: '#/components/requestBodies/PickUpCardsFromDiscardPileRequest'
      responses:
        '200':
          $ref: '#/components/responses/CardsResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'


components:
  schemas:
    HealthCheck:
      type: object
      properties:
        checks:
          type: array
          items:
            $ref: "#/components/schemas/HealthCheckProcedure"
        outcome:
          type: string
    HealthCheckProcedure:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
    Game:
      type: object
      properties:
        gameId:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - BURRACO
        status:
          type: string
          enum:
            - DRAFT
            - STARTED
            - RUNNING
            - ENDED
        player:
          type: array
          items:
            $ref: "#/components/schemas/PlayerId"
    PlayerId:
      type: string
      format: uuid
    Card:
      type: object
      properties:
        cardId:
          type: string
          description: 'Card identifier in format Suit-Rank (e.g., Heart-A, Pike-K)'
        suit:
          type: string
          description: 'Card suit'
          enum:
            - Heart
            - Tile
            - Clover
            - Pike
            - Jolly
        rank:
          type: string
          description: 'Card rank'
        cardType:
          type: string
          enum:
            - STANDARD
            - JOKER
    Cards:
      type: object
      properties:
        cards:
          type: array
          items:
            $ref: '#/components/schemas/Card'
    Error:
      type: object
      properties:
        code:
          type: integer
        errorMessages:
          type: array
          items:
            type: object

  requestBodies:
    NewGameRequest:
      description: 'New Burraco game request.'
      content:
        application/json:
          schema:
            type: object
            required:
              - gameType
            properties:
              gameType:
                type: string
                enum:
                  - BURRACO

    AddPlayerRequest:
      description: 'Add player request.'
      content:
        application/json:
          schema:
            type: object
            required:
              - playerId
            properties:
              playerId:
                $ref: "#/components/schemas/PlayerId"

    RequestDealCardsRequest:
      description: 'Add player request.'
      content:
        application/json:
          schema:
            type: object
            required:
              - playerId
            properties:
              playerId:
                $ref: "#/components/schemas/PlayerId"

    PickUpCardRequest:
      description: 'Pick up card request.'
      content:
        application/json:
          schema:
            type: object
            required:
              - playerId
            properties:
              playerId:
                $ref: "#/components/schemas/PlayerId"

    PickUpCardsFromDiscardPileRequest:
      description: 'Pick up cards from discard pile request.'
      content:
        application/json:
          schema:
            type: object
            required:
              - playerId
            properties:
              playerId:
                $ref: "#/components/schemas/PlayerId"

  responses:
    HealthCheckResponse:
      description: 'Health Check response'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HealthCheck'
    NewGameResponse:
      description: 'New Burraco game response'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Game'
    GameResponse:
      description: 'Burraco game response'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Game'
    CardResponse:
      description: 'Card response'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Card'
    CardsResponse:
      description: 'Cards response'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Cards'
    ErrorResponse:
      description: 'Error response'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'